name: bundle_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0
  

dependencies:
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_picker_plus: ^1.5.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  device_info_plus: ^11.5.0
  cloud_firestore: ^5.6.11
  provider: ^6.1.5
  device_preview: ^1.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  # ios
  image_path: "assets/images/appicon.png"
  remove_alpha_ios: true
  # android
  adaptive_icon_foreground: "assets/images/appicon.png"
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground_inset: 0

flutter_native_splash:
  color: '#FFFFFF'
  image: "assets/images/appicon.png"
  android: false
  ios: true
   